package ml.dengshen.community.community.mapper;

import java.util.List;
import ml.dengshen.community.community.model.Notify;
import ml.dengshen.community.community.model.NotifyExample;
import org.apache.ibatis.annotations.Param;

public interface NotifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notify
     *
     * @mbg.generated Wed Feb 12 21:53:10 CST 2020
     */
    long countByExample(NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notify
     *
     * @mbg.generated Wed Feb 12 21:53:10 CST 2020
     */
    int deleteByExample(NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notify
     *
     * @mbg.generated Wed Feb 12 21:53:10 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notify
     *
     * @mbg.generated Wed Feb 12 21:53:10 CST 2020
     */
    int insert(Notify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notify
     *
     * @mbg.generated Wed Feb 12 21:53:10 CST 2020
     */
    int insertSelective(Notify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notify
     *
     * @mbg.generated Wed Feb 12 21:53:10 CST 2020
     */
    List<Notify> selectByExample(NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notify
     *
     * @mbg.generated Wed Feb 12 21:53:10 CST 2020
     */
    Notify selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notify
     *
     * @mbg.generated Wed Feb 12 21:53:10 CST 2020
     */
    int updateByExampleSelective(@Param("record") Notify record, @Param("example") NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notify
     *
     * @mbg.generated Wed Feb 12 21:53:10 CST 2020
     */
    int updateByExample(@Param("record") Notify record, @Param("example") NotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notify
     *
     * @mbg.generated Wed Feb 12 21:53:10 CST 2020
     */
    int updateByPrimaryKeySelective(Notify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notify
     *
     * @mbg.generated Wed Feb 12 21:53:10 CST 2020
     */
    int updateByPrimaryKey(Notify record);
}