package ml.dengshen.community.community.model;

public class Notify {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notify.id
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notify.notifier
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    private Long notifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notify.receiver
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    private Long receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notify.outerId
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    private Long outerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notify.type
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notify.gmt_create
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notify.status
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notify.id
     *
     * @return the value of t_notify.id
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notify.id
     *
     * @param id the value for t_notify.id
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notify.notifier
     *
     * @return the value of t_notify.notifier
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    public Long getNotifier() {
        return notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notify.notifier
     *
     * @param notifier the value for t_notify.notifier
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    public void setNotifier(Long notifier) {
        this.notifier = notifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notify.receiver
     *
     * @return the value of t_notify.receiver
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    public Long getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notify.receiver
     *
     * @param receiver the value for t_notify.receiver
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    public void setReceiver(Long receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notify.outerId
     *
     * @return the value of t_notify.outerId
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    public Long getOuterid() {
        return outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notify.outerId
     *
     * @param outerid the value for t_notify.outerId
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    public void setOuterid(Long outerid) {
        this.outerid = outerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notify.type
     *
     * @return the value of t_notify.type
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notify.type
     *
     * @param type the value for t_notify.type
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notify.gmt_create
     *
     * @return the value of t_notify.gmt_create
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notify.gmt_create
     *
     * @param gmtCreate the value for t_notify.gmt_create
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notify.status
     *
     * @return the value of t_notify.status
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notify.status
     *
     * @param status the value for t_notify.status
     *
     * @mbg.generated Wed Feb 12 01:22:30 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}